### ISSUE TITLE
Lock的使用

### ISSUE THREAD

**Issue by Hemitr** [chenjiandongx/mmjpg#4]
程序中使用multiprocessing模块，用pool创建多进程，为什么互斥锁用的是threading模块的，而不是multiprocessing.lock()?

**Comment by chenjiandongx** [comment]
multiprocessing 实际上是对 threading 的高级封装

**Comment by xuhuigithub** [comment]
请问你的进程锁起了什么作用，你已经使用了pool.map准备进程并为各个进程分发了任务，并不会出现冲突的任务啊

**Comment by chenjiandongx** [comment]
不加的话 图片会下载 但是不会被放到正确的文件夹里
