### ISSUE TITLE
好像采集下来的图片都不对 哪个网站防盗链了？

### ISSUE THREAD

**Issue by ifour333** [chenjiandongx/mmjpg#6]
大神能修改一下你的代码吗
让采集能用 谢谢
我不太会改

**Comment by chenjiandongx** [comment]
@ifour333 
问题已解决

**Comment by ifour333** [comment]
厉害了你 python界我只服你

**Comment by chenjiandongx** [comment]
@ifour333 只服我还不赶紧 follow 我 😄

**Comment by ifour333** [comment]
遵命 我的大神 我就服你 另外一个好像网站都打不开 了 是不是被你 大神黑客给搞挂了

**Comment by chenjiandongx** [comment]
@ifour333 世界上本没有苦逼站长 爬的人多了 便出现了苦逼站长
