### ISSUE TITLE
'latin-1' codec can't encode characters in position 0-14: ordinal not in range(256)

### ISSUE THREAD

**Issue by Murphy-Li** [chenjiandongx/mmjpg#7]
'latin-1' codec can't encode characters in position 0-14: ordinal not in range(256)
老司机带带我，我要上省城

**Comment by cccoast** [comment]
解码试试utf8，我在ubuntu 16.04 firefox python2.7 下 decode 改成urf8即可

**Comment by hyman-lee** [comment]
老司机

**Comment by hyman-lee** [comment]
hai shi buxing ei laoge

**Comment by cccoast** [comment]
.encode('utf-8').decode('utf-8') 你查看一下页面的编码，多试试， 我这样是可以的，之前说错了，不好意思

**Comment by hyman-lee** [comment]
有时间试试，谢谢
