### ISSUE TITLE
请问怎么使用啊？能否详细说下，初学PY  目前版本3.5

### ISSUE THREAD

**Issue by HadesRoys** [chenjiandongx/mmjpg#8]
请问怎么使用啊？能否详细说下，初学PY  目前版本3.5

**Comment by HadesRoys** [comment]
等你回复~

**Comment by chenjiandongx** [comment]
克隆项目 切换到项目根目录 执行 mm_crawler.py 文件

**Comment by HadesRoys** [comment]
发现好多要安装的
pip install requests   bs4等

**Comment by HadesRoys** [comment]
话说  你爬虫1和2啥区别啊

**Comment by chenjiandongx** [comment]
pip install -r requirements.txt 安装所有依赖，爬虫 1 和爬虫 2 爬取的是不同的网站
